CC = g++
CFLAGS = -Wall -fPIC -g -Isrc -IBenoit/src
OBJECTS = Neuron_base.o Neuron_input.o Neuron_linear.o Neuron_sigmoid.o NeuralNet.o
SHARED_LIB = Alexander.so

$(SHARED_LIB): $(OBJECTS)
$(CC) $(SHARED_LIB) $(OBJECTS)

Neuron_base.o : Neuron_base.h Neuron_base.cpp Node.h
$(CC) $(CFLAGS) -c Neuron_base.cpp

Neuron_input.o : Neuron_input.h Neuron_base.h
$(CC) $(CFLAGS) -c Neuron_input.h

Neuron_linear.o : Neuron_linear.h Neuron_base.h
$(CC) $(CFLAGS) -c Neuron_linear.h

Neuron_sigmoid.o : Neuron_sigmoid.h Neuron_base.h
$(CC) $(CFLAGS) -c Neuron_sigmoid.h

NeuralNet.o : NeuralNet.h NeuralNet.cpp Neuron_base.h Neuron_input.h Index.h
$(CC) $(CFLAGS) -c NeuralNet.cpp

clean:
$(RM) $(OBJECTS)
$(RM) $(SHARED_LIB)

